### ISSUE TITLE
Support for recent versions of servant?

### ISSUE THREAD

**Issue by peti** [dmjio/google-translate#8]
We cannot compile and distribute this package in openSUSE because it depends on out-dated versions of servant:

~~~
[  122s] Setup: Encountered missing dependencies:
[  122s] servant >=0.7 && <0.11, servant-client >=0.7 && <0.11
~~~

Is there any chance that you could publish an update to Hackage that adds support for more recent versions of servant?

**Comment by dmjio** [comment]
@peti, bumped `servant` version, `google-translate-0.4.1` on hackage should compile with latest.

**Comment by dmjio** [comment]
If not, we can re-open.
